---
- name: Install required npm packages
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Install Express package
      community.general.npm:
        name: express
        path: ./
        version: '^4.17.1'
